### ISSUE TITLE
XGAP has a new homepage

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap-distribution#14] opened 2016-02-29 09:21 UTC
XGAP has a new homepage: <https://gap-packages.github.io/xgap>

Since I have no access to the old homepage, this will have to be moved manually.

**Comment by alex-konovalov** [comment] 2016-02-29 09:45
Resolved in https://github.com/gap-system/gap-distribution/commit/d38d23c0424090e2510280d30439858fdf7bf3c0

**Closed by alex-konovalov** 2016-02-29 09:45 UTC

**Comment by alex-konovalov** [comment] 2016-02-29 12:07
@fingolfin : FYI, that's what I see in the log after that:
```
*** Package XGAP - different PackageInfo.g URL:
 Our   : https://gap-packages.github.io/xgap
 Stored: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/xgap4/PackageInfo.g
Set URL of PackageInfo.g for package XGAP to
      https://gap-packages.github.io/xgap
```

**Comment by fingolfin** [comment] 2016-02-29 12:11
I am not quite sure if this is just a notice, or whehter you are informing me that something is wrong?

It looks indeed a bit weird... shouldn't that be https://gap-packages.github.io/xgap/PackageInfo.g instead of https://gap-packages.github.io/xgap ?

**Comment by alex-konovalov** [comment] 2016-02-29 12:20
Hm, was intended as just a notice. But indeed you pointed out that there was a missing `PackageInfo.g` - I have just figured out that myself when read the rest of the log. fixed now.

BTW, when package moves, I need not the website of the package but the URL of PackageInfo.g - that saves my time from downloading the release and checking which URL is specified in the PackageInfo.g file. It's not necessarily the concatenation of the two.
